In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
from tensorflow import keras

#tf version should be 2.2 or higher
tf.__version__

'2.3.0'

In [2]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [4]:
#setup model
model = keras.Sequential([
    keras.layers.Reshape(input_shape=(28*28,), target_shape=(28, 28, 1)),
    #keras.layers.Flatten(input_shape=(28, 28, 1)),
    keras.layers.Conv2D(12, kernel_size=3, use_bias= False, padding='same',activation=tf.nn.relu, input_shape=(28,28,1)),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Conv2D(24, kernel_size=5, use_bias= False, padding='same', strides=2, activation=tf.nn.relu),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Conv2D(36, kernel_size=5, use_bias= False, padding='same', strides=2, activation=tf.nn.relu),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Flatten(),
    keras.layers.Dense(256, activation = tf.nn.relu),
    keras.layers.BatchNormalization(center=True, scale=False),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(10, activation = tf.nn.softmax)
])

In [5]:
#compile model
model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [6]:
#train model
model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1277 - accuracy: 0.9607
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0528 - accuracy: 0.9833
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0401 - accuracy: 0.9870
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0344 - accuracy: 0.9891
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0281 - accuracy: 0.9911
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0230 - accuracy: 0.9931
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0199 - accuracy: 0.9934
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0182 - accuracy: 0.9944
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0139 - accuracy: 0.9958
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.013

In [7]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc*100)

313/313 [==============================] - 1s 2ms/step - loss: 0.0237 - accuracy: 0.9934

Test accuracy: 99.3399977684021


In [8]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

In [9]:
#Raw predictions
predictions

array([[1.63375521e-10, 1.17461120e-07, 3.43269932e-07, 3.51638096e-06,
        2.78625816e-08, 5.68512348e-09, 4.73269868e-09, 9.99995828e-01,
        7.77229892e-10, 2.73084964e-07],
       [1.34298705e-09, 1.56997704e-08, 1.00000000e+00, 2.29093068e-12,
        2.11234871e-12, 1.61180089e-15, 5.12841813e-09, 2.39480094e-12,
        4.46578191e-12, 1.07577109e-12],
       [1.30047029e-10, 9.99999523e-01, 4.90917387e-08, 2.55595083e-08,
        1.18373835e-08, 7.02403682e-08, 2.92387980e-08, 2.85336455e-07,
        5.81371751e-09, 8.51857251e-09],
       [1.00000000e+00, 4.99377896e-14, 1.21952823e-10, 3.52696605e-13,
        1.84105682e-12, 5.27189473e-11, 2.30175790e-08, 1.28798144e-12,
        1.70595815e-10, 2.01740673e-11],
       [1.51371538e-08, 7.55257801e-10, 4.60285543e-09, 5.41609188e-11,
        9.99993801e-01, 1.32811692e-10, 3.62419854e-08, 1.77802910e-08,
        1.47823220e-09, 6.22535663e-06]], dtype=float32)

In [10]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [11]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
